version: '3'
services:
  frontend:
    image: asb-ui:latest
    container_name: asb-ui
    networks:
      - app_network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env

networks:
  app_network:
    driver: bridge
