version: '2.4'
services:
  frontend:
    image: asb-ui:latest
    container_name: asb-ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - /var/www/shared/env/.env
    networks:
      - app_network

networks:
  app_network:
    external: true