name: Build and Deploy Next.js Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_URL: http://0.0.0.0:8000
      AUTHORIZATION: asb

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Build application
        run: npm run build
