name: Build and Deploy Next.js Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ASB_BASE_URL: http://0.0.0.0:8000
      ASB_KEY_URL: asb
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
      NEXT_PUBLIC_CLOUDINARY_API_KEY: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_API_KEY }}
      NEXT_PUBLIC_CLOUDINARY_API_SECRET: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_API_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Start backend server
        run: npm run start-backend &
        # Run the backend server in the background

      - name: Wait for backend to be ready
        run: |
          while ! nc -z localhost 8000; do
            sleep 1
          done

      - name: Build the Next.js application
        run: npm run build
