name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache-deps
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./package-lock.json') }}
      - name: Install locked dependencies
        run: npm install --frozen-lockfile

  lint:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Restore cached dependencies
        uses: actions/cache@v3
        id: restore-deps
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./package-lock.json') }}
      - name: Run Eslint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Restore cached dependencies
        uses: actions/cache@v3
        id: restore-deps
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./package-lock.json') }}
      - name: Transpile
        run: npm run build
